server:
  port: 8040
spring:
  data:
    mongodb:
      username: koko
      password: password123
      host: localhost
      port: 27017
      database: notification
      authentication-database: admin
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: paymentGroup,orderGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: orderConfirmation:org.micro.notification.core.kafka.order.dto.OrderConfirmation,paymentConfirmation:org.micro.notification.core.kafka.payment.dto.PaymentConfirmation
  mail:
    host: localhost
    port: 1025
    username: koko
    password: password123
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
    contact:
      name: contact@zakkestore.com