spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/payments
    username: koko
    password: password123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    topic:
      name: payment-topic
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: paymentConfirmation:org.micro.ecommerce.notification.PaymentNotificationRequest

application:
  config:
    product-url: http://localhost:8222/api/v1/products

server:
  port: 8060